version: '3.8'

services:

    app:
        build: ./app
        ports:
            - 8000:8000
        command: uvicorn main:app --host=0.0.0.0 --reload
        volumes:
            - ./app:/usr/src/app
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_BROKER_BACKEND=redis://redis:6378/0
        depends_on:
            - redis
    worker:
        build: ./app
        command: celery --app=worker.celery worker --loglevel=info --logfile=logs/celery.log
        volumes:
            - ./app:/usr/src/app
        depends_on:
            - web
            - redis
    redis:
        image: redis:6-alpine