version: '3.8'

services:

  a_service:
    build: ./app
    ports:
      - 15566:15566
    #networks:
    #  - mgmt_network
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 15566 --reload
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - db
  worker:
    build: ./app
    #networks:
    #  - mgmt_network
    command: poetry run celery --app worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env
    depends_on:
      - a_service
      - redis

  redis:
    image: redis:6-alpine
    #networks:
    #  - mgmt_network

  dashboard:
    build: ./app
    command: poetry run celery flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
    #networks:
    #  - mgmt_network
    ports:
      - 5556:5555
    env_file:
      - ./app/.env
    depends_on:
      - a_service
      - redis
      - worker

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    expose:
      - 5432
    
volumes:
  postgres_data:

#networks:
#  mgmt_network:
#    driver: bridge
#    name: mgmt_network